### ISSUE TITLE
Examples on source and data

### ISSUE THREAD

**Issue by SurKM9** [lemire/lbimproved#4]
Could you post a simple example on how to use this as library? Moreover, a sample on how the data and class labels should look like. It would help others immensely.

**Comment by lemire** [comment]
> Could you post a simple example on how to use this as library?

Done:
https://github.com/lemire/lbimproved/blob/master/example.cpp

> Moreover, a sample on how the data and class labels should look like. It would help others immensely

The library just seeks nearest neighbors between same-size arrays. If you want to use it for classification, that's a higher level concept, but it should not prove difficult. 

I'll close this issue. If you can narrow down your question, ideally with code samples, I'll be glad to  follow up.
